spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=explorer;encrypt=true;trustServerCertificate=true;
    username: explorer
    password: explorer
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history
    default-schema: dbo
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost:4200}


